name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/commit
      description: Output of `resonix-node --version` or commit hash
  - type: input
    id: os
    attributes:
      label: OS
      description: e.g., Windows 11, Ubuntu 24.04
  - type: dropdown
    id: resolver
    attributes:
      label: Resolver enabled
      options: ["yes", "no", "unknown"]
  - type: textarea
    id: config
    attributes:
      label: Relevant config
      description: Snippet from resonix.toml (redact secrets)
      render: text
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Be specific and include logs when possible
      placeholder: |
        1. config ...
        2. call POST /players with ...
        3. connect WS ...
        4. observe ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant server logs around the time of the issue
      render: text
